### ISSUE TITLE
Inverted Images Exhibit Droopy Eyes

### ISSUE THREAD

**Issue by falloncandra** [omertov/encoder4editing#38] opened 2021-06-25 20:31 UTC
Hi,

I am trying to use the provided E4E model pre-trained on FFHQ dataset to invert CelebA images into latent codes and generated them back. However, I found that all reconstructed face images exhibit droopy eyes, unlike the originals. do you know what is the cause and probably, how to fix it? 

Thank you very much!

Examples:
 
![182643](https://user-images.githubusercontent.com/11532884/123481909-50436100-d5fc-11eb-8b44-b2a9a1f9d234.jpg)
![inv_5](https://user-images.githubusercontent.com/11532884/123481911-51748e00-d5fc-11eb-945e-2e38e86d21f5.jpg)

![182646](https://user-images.githubusercontent.com/11532884/123481937-59ccc900-d5fc-11eb-9b4d-43dcdca2ba52.jpg)
![inv_8](https://user-images.githubusercontent.com/11532884/123481938-5afdf600-d5fc-11eb-995d-ee9dab3f94fc.jpg)

![182649](https://user-images.githubusercontent.com/11532884/123481957-63563100-d5fc-11eb-9c08-64b7f65590d4.jpg)
![inv_11](https://user-images.githubusercontent.com/11532884/123481960-64875e00-d5fc-11eb-8b5c-6210583d04d8.jpg)

![182651](https://user-images.githubusercontent.com/11532884/123481978-6a7d3f00-d5fc-11eb-9737-73807b3a8cab.jpg)
![inv_13](https://user-images.githubusercontent.com/11532884/123481981-6bae6c00-d5fc-11eb-8a27-0d39f527687b.jpg)

**Comment by omertov** [comment] 2021-06-29 11:12
Hi @falloncandra,
I believe the problem is that the input images are not aligned according to the FFHQ alignment process, try running the ffhq alignment for each image before the inversion (see the collab for an exmaple)

Best,
Omer

**Comment by falloncandra** [comment] 2021-06-30 16:48
Hi, I have tried running the FFHQ alignment process as you suggested, and it worked! 
Thank you very much :)

![182637-inv-inv](https://user-images.githubusercontent.com/11532884/124000152-31ade300-d9cb-11eb-911b-d795f7375de2.jpg)
![182638-inv](https://user-images.githubusercontent.com/11532884/124000169-35416a00-d9cb-11eb-9fbe-2d3f257ea929.jpg)
![043610-inv-inv](https://user-images.githubusercontent.com/11532884/124000340-5dc96400-d9cb-11eb-8c07-4de575d8327c.jpg)

**Comment by omertov** [comment] 2021-07-05 10:46
Awsome! closing the issue :)

**Closed by omertov** 2021-07-05 10:46 UTC
